[build]
builder = "nixpacks"
buildCommand = "dotnet restore Wefaaq.Api/Wefaaq.Api.csproj && dotnet publish Wefaaq.Api/Wefaaq.Api.csproj -c Release -o out"

[deploy]
startCommand = "cd out && dotnet Wefaaq.Api.dll"
